language: rust
sudo: false

INSTALL_NODE_VIA_NVM: &INSTALL_NODE_VIA_NVM
                        |
                        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
                        source ~/.nvm/nvm.sh
                        nvm install 16.17.0

cache:
  directories:
    - /home/travis/.cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

matrix:
  include:
    - name: Page
      rust: stable
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      install:
        - *INSTALL_NODE_VIA_NVM
      script:
        - mkdir -p docs
        - rm -rf ./docs/*
        - wasm-pack build
        - cd www && npm install
        - npm run build
        - mv ./dist/* ../docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs
        keep-history: false

notifications:
  email:
    on_success: never
